DROP TABLE IF EXISTS `#__linkr_bookmarks`;

CREATE TABLE `#__linkr_bookmarks` (
	`id` int(5) unsigned NOT NULL auto_increment,
	`name` varchar(20) NOT NULL default '',
	`text` varchar(50) NOT NULL default '',
	`size` varchar(20) NOT NULL default 'text',
	`htmltext` tinytext NOT NULL default '',
	`htmlsmall` tinytext NOT NULL default '',
	`htmllarge` tinytext NOT NULL default '',
	`htmlbutton` text NOT NULL default '',
	`htmlcustom` text NOT NULL default '',
	`ordering` tinyint(2) NOT NULL default '0',
	`icon` varchar(100) NOT NULL default '',
	`popular` int(1) NOT NULL default '0',
	PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


INSERT INTO `#__linkr_bookmarks` (`name`, `text`, `size`, `htmltext`, `htmlsmall`, `htmllarge`, `htmlbutton`, `htmlcustom`, `ordering`, `icon`, `popular`) VALUES
('Digg', 'Digg This!', 'text', '<a href="http://digg.com/submit?url=[url]&title=[title]&bodytext=[desc]" target="_blank">[text]</a>', '<a href="http://digg.com/submit?url=[url]&title=[title]&bodytext=[desc]" target="_blank">\r\n<img src="[badgespath]/digg.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://digg.com/submit?url=[url]&title=[title]&bodytext=[desc]" target="_blank">\r\n<img src="[badgespath]/digg.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '<script type="text/javascript">\r\ndigg_skin=''compact'';\r\ndigg_url=[url-js];\r\n</script>\r\n<script src="http://digg.com/tools/diggthis.js" type="text/javascript"></script>', '<script type="text/javascript">\r\ndigg_url=[url-js];\r\n</script>\r\n<script src="http://digg.com/tools/diggthis.js" type="text/javascript"></script>', 4, 'components/com_linkr/assets/badges/digg.small.gif', 1),
('Del.icio.us', 'Add to Del.icio.us', 'text', '<a href="http://del.icio.us/post?url=[url]&title=[title]" target="_blank">[text]</a>', '<a href="http://del.icio.us/post?url=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/delicious.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://del.icio.us/post?url=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/delicious.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '<a href="http://del.icio.us/post?url=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/delicious.button.gif" alt="[text]" border="0" />\r\n</a>', '', 7, 'components/com_linkr/assets/badges/delicious.small.gif', 1),
('Reddit', 'Reddit', 'text', '<a href="http://reddit.com/submit?url=[url]&title=[title]" target="_blank">[text]</a>', '<a href="http://reddit.com/submit?url=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/reddit.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://reddit.com/submit?url=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/reddit.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '<a href="http://reddit.com/submit?url=[url]&title=[title]" target="_blank">\r\n<img src="http://www.reddit.com/static/spreddit7.gif" alt="[text]" border="0" />\r\n</a>', '<script type="text/javascript" src="http://www.reddit.com/button.js?t=3"></script>', 17, 'components/com_linkr/assets/badges/reddit.small.gif', 1),
('Newsvine', 'Seed Newsvine', 'text', '<a href="http://www.newsvine.com/_wine/save?popoff=0&u=[url]&h=[title]" target="_blank">[text]</a>', '<a href="http://www.newsvine.com/_wine/save?popoff=0&u=[url]&h=[title]" target="_blank">\r\n<img src="http://www.newsvine.com/_vine/images/identity/button_seednewsvine.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://www.newsvine.com/_wine/save?popoff=0&u=[url]&h=[title]" target="_blank">\r\n<img src="[badgespath]/newsvine.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '', '', 16, 'components/com_linkr/assets/badges/newsvine.small.gif', 1),
('Furl', 'Furl', 'text', '<a href="http://www.furl.net/storeIt.jsp?t=[title]&u=[url]" target="_blank">[text]</a>', '<a href="http://www.furl.net/storeIt.jsp?t=[title]&u=[url]" target="_blank">\r\n<img src="[badgespath]/furl.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://www.furl.net/storeIt.jsp?t=[title]&u=[url]" target="_blank">\r\n<img src="[badgespath]/furl.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '', '', 14, 'components/com_linkr/assets/badges/furl.small.gif', 0),
('BlinkList', 'BlinkList', 'text', '<a href="http://www.blinklist.com/index.php?Action=Blink/addblink.php&Url=[url]&Title=[title]" target="_blank">[text]</a>', '<a href="http://www.blinklist.com/index.php?Action=Blink/addblink.php&Url=[url]&Title=[title]" target="_blank">\r\n<img src="[badgespath]/blinklist.small.gif" border="0" width="16" height="16" />\r\n</a>', '<a href="http://www.blinklist.com/index.php?Action=Blink/addblink.php&Url=[url]&Title=[title]" target="_blank">\r\n<img src="[badgespath]/blinklist.large.gif" border="0" width="32" height="32" />\r\n</a>', '', '', 13, 'components/com_linkr/assets/badges/blinklist.small.gif', 0),
('Yahoo MyWeb', 'Yahoo MyWeb', 'text', '<a href="http://myweb2.search.yahoo.com/myresults/bookmarklet?t=[title]&u=[url]" target="_blank">[text]</a>', '<a href="http://myweb2.search.yahoo.com/myresults/bookmarklet?t=[title]&u=[url]" target="_blank">\r\n<img src="[badgespath]/yahoo.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://myweb2.search.yahoo.com/myresults/bookmarklet?t=[title]&u=[url]" target="_blank">\r\n<img src="[badgespath]/yahoo.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '<script language="javascript" src="http://sm.feeds.yahoo.com/Buttons/V1.0/yactions.js"></script>\r\n<script language="javascript">yactions.buildButton(''save'', ''My_Web'');</script>', '<script language="javascript" src="http://sm.feeds.yahoo.com/Buttons/V1.0/yactions.js"></script>\r\n<script language="javascript">yactions.buildButton(''save'', ''My_Web'');</script>', 12, 'components/com_linkr/assets/badges/yahoo.small.gif', 0),
('Google', 'Google', 'text', '<a href="http://www.google.com/bookmarks/mark?op=edit&bkmk=[url]&title=[title]" target="_blank">[text]</a>', '<a href="http://www.google.com/bookmarks/mark?op=edit&bkmk=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/google.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://www.google.com/bookmarks/mark?op=edit&bkmk=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/google.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '', '', 11, 'components/com_linkr/assets/badges/google.small.gif', 0),
('Diigo', 'Diigo', 'text', '<a href="http://www.diigo.com/post?url=[url]&title=[title]" target="_blank">[text]</a>', '<a href="http://www.diigo.com/post?url=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/diigo.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://www.diigo.com/post?url=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/diigo.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '', '', 10, 'components/com_linkr/assets/badges/diigo.small.gif', 0),
('StumbleUpon', 'Stumble It!', 'text', '<a href="http://www.stumbleupon.com/submit?url=[url]&title=[title]" target="_blank">[text]</a>', '<a href="http://www.stumbleupon.com/submit?url=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/stumbleupon.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://www.stumbleupon.com/submit?url=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/stumbleupon.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '<a href="http://www.stumbleupon.com/submit?url=[url]&title=[title]" target="_blank">\r\n<img border=0 src="http://cdn.stumble-upon.com/images/120x20_su_white.gif" alt="[text]" border="0" />\r\n</a>', '', 9, 'components/com_linkr/assets/badges/stumbleupon.small.gif', 1),
('Mr. Wong', 'Mr. Wong', 'text', '<a href="http://www.mister-wong.de/index.php?action=addurl&bm_url=[url]&bm_description=[title]" target="_blank">[text]</a>', '<a href="http://www.mister-wong.de/index.php?action=addurl&bm_url=[url]&bm_description=[title]" target="_blank">\r\n<img src="[badgespath]/misterwong.small.gif" border="0" width="16" height="16" alt="[text]" />\r\n</a>', '<a href="http://www.mister-wong.de/index.php?action=addurl&bm_url=[url]&bm_description=[title]" target="_blank">\r\n<img src="[badgespath]/misterwong.large.gif" border="0" width="32" height="32" alt="[text]" />\r\n</a>', '<a href="http://www.mister-wong.de/index.php?action=addurl&bm_url=[url]&bm_description=[title]" target="_blank">\r\n<img src="http://www.mister-wong.com/img/en/buttons/btn_1.gif" alt="[text]" border="0" />\r\n</a>', '', 8, 'components/com_linkr/assets/badges/misterwong.small.gif', 0),
('Technorati', 'Add to Faves!', 'text', '<a href="http://technorati.com/faves?add=[url]" target="_blank">[text]</a>', '<a href="http://technorati.com/faves?add=[url]" target="_blank">\r\n<img src="[badgespath]/technorati.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://technorati.com/faves?add=[url]" target="_blank">\r\n<img src="[badgespath]/technorati.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '', '', 6, 'components/com_linkr/assets/badges/technorati.small.gif', 1),
('Facebook', 'Share on Facebook', 'text', '<a href="http://www.facebook.com/sharer.php?u=[url]&t=[title]" target="_blank">[text]</a>', '<a href="http://www.facebook.com/sharer.php?u=[url]&t=[title]" target="_blank">\r\n<img src="[badgespath]/facebook.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://www.facebook.com/sharer.php?u=[url]&t=[title]" target="_blank">\r\n<img src="[badgespath]/facebook.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '<script>function fbs_click() {window.open(''http://www.facebook.com/sharer.php?u=[url]&t=[title]'',''sharer'',''toolbar=0,status=0,width=626,height=436'');return false;}</script><style> html .fb_share_button { display: -moz-inline-block; display:inline-block; padding:1px 20px 0 5px; height:15px; border:1px solid #d8dfea; background:url(http://static.ak.fbcdn.net/images/share/facebook_share_icon.gif?7:26981) no-repeat top right; } html .fb_share_button:hover { color:#fff; border-color:#295582; background:#3b5998 url(http://static.ak.fbcdn.net/images/share/facebook_share_icon.gif?7:26981) no-repeat top right; text-decoration:none; } </style> <a href="http://www.facebook.com/share.php?u=[url]" class="fb_share_button" onclick="return fbs_click()" target="_blank" style="text-decoration:none;">[text]</a>', '', 5, 'components/com_linkr/assets/badges/facebook.small.gif', 1),
('Slashdot', 'Slashdot', 'text', '<a href="http://slashdot.org/submit.pl?url=[url]&subj=[title]&story=[desc]" target="_blank">[text]</a>', '<a href="http://slashdot.org/submit.pl?url=[url]&subj=[title]&story=[desc]" target="_blank">\r\n<img src="[badgespath]/slashdot.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://slashdot.org/submit.pl?url=[url]&subj=[title]&story=[desc]" target="_blank">\r\n<img src="[badgespath]/slashdot.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '', '<script src="http://slashdot.org/slashdot-it.js" type="text/javascript"></script>', 18, 'components/com_linkr/assets/badges/slashdot.small.gif', 0),
('Twitter', 'Update Twitter status', 'text', '<a href="http://twitter.com/home?status=[title]+[url]" target="_blank">[text]</a>', '<a href="http://twitter.com/home?status=[title]+[url]" target="_blank">\r\n<img src="[badgespath]/twitter.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://twitter.com/home?status=[title]+[url]" target="_blank">\r\n<img src="[badgespath]/twitter.large.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '', '', 3, 'components/com_linkr/assets/badges/twitter.small.gif', 1),
('MySpace', 'Post to MySpace', 'text', '<a href="http://www.myspace.com/Modules/PostTo/Pages/?u=[url]&t=[title]&c=[desc]" target="_blank">[text]</a>', '<a href="http://www.myspace.com/Modules/PostTo/Pages/?u=[url]&t=[title]&c=[desc]" target="_blank">\r\n<img src="[badgespath]/myspace.small.gif" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://www.myspace.com/Modules/PostTo/Pages/?u=[url]&t=[title]&c=[desc]" target="_blank">\r\n<img src="[badgespath]/myspace.gif" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '', '', 2, '', 1),
('Weblinkr', 'Save to Weblinkr', 'text', '<a href="http://weblinkr.com/add/?popup=1&address=[url]&title=[title]" target="_blank">[text]</a>', '<a href="http://weblinkr.com/add/?popup=1&address=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/weblinkr.small.png" alt="[text]" border="0" width="16" height="16" />\r\n</a>', '<a href="http://weblinkr.com/add/?popup=1&address=[url]&title=[title]" target="_blank">\r\n<img src="[badgespath]/weblinkr.large.png" alt="[text]" border="0" width="32" height="32" />\r\n</a>', '', '', 1, 'components/com_linkr/assets/badges/weblinkr.small.png', 0);
